INSERT INTO book (id, title, author, cover) VALUES (1, '1984', 'George Orwell', 'https://papiro-spring-api.herokuapp.com/api/images/1_cover.jpg')
INSERT INTO book (id, title, author, cover) VALUES (2, 'A Metamorfose', 'Franz Kafka', 'https://papiro-spring-api.herokuapp.com/api/images/2_cover.jpg')
INSERT INTO book (id, title, author, cover) VALUES (3, 'A Divina Comédia', 'Dante', 'https://papiro-spring-api.herokuapp.com/api/images/3_cover.jpg')
INSERT INTO book (id, title, author, cover) VALUES (4, 'D.Quixote de La Mancha', 'Miguel de Cervantes', 'https://papiro-spring-api.herokuapp.com/api/images/4_cover.jpg')
INSERT INTO book (id, title, author, cover) VALUES (5, 'História de Portugal, das Origens até 1940', 'João Ameal', 'https://papiro-spring-api.herokuapp.com/api/images/5_cover.jpg')
INSERT INTO book (id, title, author, cover) VALUES (6, 'História Concisa de Portugal', 'José Hermano Saraiva', 'https://papiro-spring-api.herokuapp.com/api/images/6_cover.jpg')
INSERT INTO book (id, title, author, cover) VALUES (7, 'Imitação de Cristo', 'Tomás de Kempis', 'https://papiro-spring-api.herokuapp.com/api/images/7_cover.jpg')
INSERT INTO book (id, title, author, cover) VALUES (8, 'Livro do Desassossego', 'Fernando Pessoa', 'https://papiro-spring-api.herokuapp.com/api/images/8_cover.jpg')
INSERT INTO book (id, title, author, cover) VALUES (9, 'Os Lusíadas', 'Luís de Camões', 'https://papiro-spring-api.herokuapp.com/api/images/9_cover.jpg')
INSERT INTO book (id, title, author, cover) VALUES (10, 'Mensagem', 'Fernando Pessoa', 'https://papiro-spring-api.herokuapp.com/api/images/10_cover.jpg')
INSERT INTO book (id, title, author, cover) VALUES (11, 'Odisseia', 'Homero', 'https://papiro-spring-api.herokuapp.com/api/images/11_cover.jpg')
INSERT INTO book (id, title, author, cover) VALUES (12, 'Os Maias', 'Eça de Queirós', 'https://papiro-spring-api.herokuapp.com/api/images/12_cover.jpg')
INSERT INTO book (id, title, author, cover) VALUES (13, 'Sonetos', 'Luís de Camões', 'https://papiro-spring-api.herokuapp.com/api/images/13_cover.jpg')


INSERT INTO users (id, username, password, firstname, lastname) VALUES (1, 'admin', 'admin123', 'Admin', 'Admin')
INSERT INTO users (id, username, password, firstname, lastname) VALUES (2, 'tiago', 'tiago123', 'Tiago', 'Pinto')
INSERT INTO users (id, username, password, firstname, lastname) VALUES (3, 'user3', '123', 'Tiago', 'Pinto')
INSERT INTO users (id, username, password, firstname, lastname) VALUES (4, 'user4', '123', 'Tiago', 'Pinto')
INSERT INTO users (id, username, password, firstname, lastname) VALUES (5, 'user5', '123', 'Tiago', 'Pinto')
INSERT INTO users (id, username, password, firstname, lastname) VALUES (6, 'user6', '123', 'Tiago', 'Pinto')
INSERT INTO users (id, username, password, firstname, lastname) VALUES (7, 'user7', '123', 'Tiago', 'Pinto')
INSERT INTO users (id, username, password, firstname, lastname) VALUES (8, 'user8', '123', 'Tiago', 'Pinto')
INSERT INTO users (id, username, password, firstname, lastname) VALUES (9, 'user9', '123', 'Tiago', 'Pinto')
INSERT INTO users (id, username, password, firstname, lastname) VALUES (10, 'user10', '123', 'Tiago', 'Pinto')
