INSERT INTO book ( title, author, cover) VALUES ( '1984', 'George Orwell', 'https://papiro-spring-api.herokuapp.com/api/images/1_cover.jpg')
INSERT INTO book ( title, author, cover) VALUES ( 'A Metamorfose', 'Franz Kafka', 'https://papiro-spring-api.herokuapp.com/api/images/2_cover.jpg')
INSERT INTO book ( title, author, cover) VALUES ( 'A Divina Comédia', 'Dante', 'https://papiro-spring-api.herokuapp.com/api/images/3_cover.jpg')
INSERT INTO book ( title, author, cover) VALUES ( 'D.Quixote de La Mancha', 'Miguel de Cervantes', 'https://papiro-spring-api.herokuapp.com/api/images/4_cover.jpg')
INSERT INTO book ( title, author, cover) VALUES ( 'História de Portugal, das Origens até 1940', 'João Ameal', 'https://papiro-spring-api.herokuapp.com/api/images/5_cover.jpg')
INSERT INTO book ( title, author, cover) VALUES ( 'História Concisa de Portugal', 'José Hermano Saraiva', 'https://papiro-spring-api.herokuapp.com/api/images/6_cover.jpg')
INSERT INTO book ( title, author, cover) VALUES ( 'Imitação de Cristo', 'Tomás de Kempis', 'https://papiro-spring-api.herokuapp.com/api/images/7_cover.jpg')
INSERT INTO book ( title, author, cover) VALUES ( 'Livro do Desassossego', 'Fernando Pessoa', 'https://papiro-spring-api.herokuapp.com/api/images/8_cover.jpg')
INSERT INTO book ( title, author, cover) VALUES ( 'Os Lusíadas', 'Luís de Camões', 'https://papiro-spring-api.herokuapp.com/api/images/9_cover.jpg')
INSERT INTO book ( title, author, cover) VALUES ( 'Mensagem', 'Fernando Pessoa', 'https://papiro-spring-api.herokuapp.com/api/images/10_cover.jpg')
INSERT INTO book ( title, author, cover) VALUES ( 'Odisseia', 'Homero', 'https://papiro-spring-api.herokuapp.com/api/images/11_cover.jpg')
INSERT INTO book ( title, author, cover) VALUES ( 'Os Maias', 'Eça de Queirós', 'https://papiro-spring-api.herokuapp.com/api/images/12_cover.jpg')
INSERT INTO book ( title, author, cover) VALUES ( 'Sonetos', 'Luís de Camões', 'https://papiro-spring-api.herokuapp.com/api/images/13_cover.jpg')


INSERT INTO users ( username, password, firstname, lastname) VALUES ( 'admin', 'admin123', 'Admin', 'Admin')
INSERT INTO users ( username, password, firstname, lastname) VALUES ( 'tiago', 'tiago123', 'Tiago', 'Pinto')
INSERT INTO users ( username, password, firstname, lastname) VALUES ( 'user3', '123', 'Tiago', 'Pinto')
INSERT INTO users ( username, password, firstname, lastname) VALUES ( 'user4', '123', 'Tiago', 'Pinto')
INSERT INTO users ( username, password, firstname, lastname) VALUES ( 'user5', '123', 'Tiago', 'Pinto')
INSERT INTO users ( username, password, firstname, lastname) VALUES ( 'user6', '123', 'Tiago', 'Pinto')
INSERT INTO users ( username, password, firstname, lastname) VALUES ( 'user7', '123', 'Tiago', 'Pinto')
INSERT INTO users ( username, password, firstname, lastname) VALUES ( 'user8', '123', 'Tiago', 'Pinto')
INSERT INTO users ( username, password, firstname, lastname) VALUES ( 'user9', '123', 'Tiago', 'Pinto')
INSERT INTO users ( username, password, firstname, lastname) VALUES ( 'user10', '123', 'Tiago', 'Pinto')
